# Generated by Django 3.2.3 on 2021-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('author_first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('author_last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
